#! /bin/bash

bspc config border_width        0
bspc config window_gap          5

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc monitor LVDS -d 1 2 3 4 5

sxhkd &
