#! /bin/bash

bspc config border_width        0
bspc config window_gap          10
bspc config top_padding         26

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc monitor VGA1 -d 1 2 3 4 5 6 7 8 9 10

sxhkd &

xsetroot -cursor_name left_ptr &
