#! /bin/sh

sxhkd &

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config bottom_padding 22

bspc monitor -d I II III IV V VI VII VIII IX X